cards_per_turn: 3
random_seed: 5
show_messages: false

    
env:
  action_log_file: action_log.csv

  max_global_history_length: 10 # Maximum number of actions to keep in the global history
  action_repeat_threshold: 2 # Number of times an action must be repeated before it is considered a loop
  stagnation_threshold: 10 # Number of actions to take without making progress before the game is considered to be stuck
  