dqn:
  total_timesteps: 50000
  learning_rate: 0.001
  learning_starts: 10000
  batch_size: 32
  buffer_size: 10000
  exploration_fraction: 0.1
  exploration_final_eps: 0.02
  target_update_interval: 1000

cards_per_turn: 3
random_seed: 5
show_messages: false

    
env:
  log_path: /mnt/c/logs # Path to save logs
  save_every: 100000 # Save the game state every n actions
  stagnation_threshold: 1000 # Number of actions to take without making progress before the game checks for available moves
  max_steps: 200000 # Maximum number of steps to take before the game is considered to be stuck
  