
# Deck
dealing_next_cards: 
  - -1
  - "Dealing next cards."
recycling_waste_pile:
  - 0
  - "Recycling waste pile."
no_cards_to_deal: 
  - -1
  - "No cards to deal."
# Moves
invalid_source: 
  - -1
  - "Invalid move: Source stack is invalid."
valid_source_invalid_destination: 
  - 1
  - "Invalid move: Source stack is valid but destination stack is invalid."
valid_source_and_valid_destination: 
  - 2
  - "Valid move."
no_cards_to_move: 
  - -1
  - "Invalid move: No cards to move."
cards_not_movable: 
  - -1
  - "Invalid move: Cards in the source stack are not movable."
cards_movable:
  - 1
  - "Invalid move: Cards in the source stack are movable."
# Foundation
invalid_foundation_move_number: 
  - 1
  - "Invalid move: Correct suit but card number must be one more than the top card of the foundation stack."
invalid_foundation_move_ace: 
  - -5
  - "Invalid move: Only aces can be moved to an empty foundation stack."
successful_foundation_move: 
  - 1000
  - "Valid move to foundation."
ace_to_foundation: 
  - 2000
  - "Valid move to empty foundation."
# Tableau
reveal_hidden_card: 
  - 1000
  - "Turning over card."
invalid_tableau_move_color: 
  - -1
  - "Invalid move: Correct number but card color must be opposite of the top card of the tableau stack."
invalid_tableau_move_number:
  - -1
  - "Invalid move: Correct color but card number must be one less than the top card of the tableau stack."
invalid_tableau_move_color_number:
  - -5
  - "Invalid move: Card color and number must be opposite and one less than the top card of the tableau stack."
invalid_tableau_move_king: 
  - -5
  - "Invalid move: Only kings can be moved to an empty tableau stack."
successful_tableau_move: 
  - 500
  - "Valid move to tableau stack."
successful_tableau_move_king:
  - 2000
  - "Valid move to empty tableau stack."
successful_tableau_transfer_king:
  - 0
  - "Valid move from one empty stack to another."
# Complete
game_complete: 
  - 10000
  - "Congratulations! You have completed the game."